### ISSUE TITLE
VideoSDcard not working

### ISSUE THREAD

**Issue by Jipolie01** [PaulStoffregen/OctoWS2811#21]
Hi guys,

I'm trying to test out the VideoSDcard file but it is not working. The program tells me that there are files detected and image frames can be found. But as soon as leds.show and leds.begin are shown the Teensy3.6 keeps restarting. Anyone got a solution for this problem?
One other question I have is how the library is being called in the file. I see no leds called (only begin and show)

**Comment by PaulStoffregen** [comment]
Ask here (not github).

https://forum.pjrc.com/forums/3-Technical-Support-amp-Questions

If you have modified the example code in *any* way, even 1 character, you must post the code in your question on the forum.  Please do not neglect that important step, because it really is essential for us to be able to help you.
